apiVersion: v1
kind: Service
metadata:
  name: {{ include "osva.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "osva.name" . }}
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "osva.name" . }}
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
