apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osva.fullname" . }}-workflow-orchestrator
  labels:
    app.kubernetes.io/name: {{ include "osva.name" . }}
    app.kubernetes.io/component: workflow-orchestrator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.workflowOrchestrator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "osva.name" . }}
      app.kubernetes.io/component: workflow-orchestrator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "osva.name" . }}
        app.kubernetes.io/component: workflow-orchestrator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "osva.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: workflow-orchestrator
          image: {{ include "osva.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["workflow-orchestrator"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "osva.fullname" . }}-env
            {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ .Values.existingSecret }}
            {{- end }}
            {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.workflowOrchestrator.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
