export const ARTIFACT_ERROR_CODES = {
  ARTIFACT_NOT_FOUND: "ARTIFACT_NOT_FOUND",
  ARTIFACT_UNAVAILABLE: "ARTIFACT_UNAVAILABLE",
  ARTIFACT_PAYLOAD_TOO_LARGE: "ARTIFACT_PAYLOAD_TOO_LARGE",
  ARTIFACT_IDEMPOTENCY_CONFLICT: "ARTIFACT_IDEMPOTENCY_CONFLICT",
  ARTIFACT_DIGEST_MISMATCH: "ARTIFACT_DIGEST_MISMATCH",
  ARTIFACT_WORKSPACE_MISMATCH: "ARTIFACT_WORKSPACE_MISMATCH",
  ARTIFACT_INVALID_REQUEST: "ARTIFACT_INVALID_REQUEST",
} as const;

export type ArtifactErrorCode =
  (typeof ARTIFACT_ERROR_CODES)[keyof typeof ARTIFACT_ERROR_CODES];

export function isArtifactErrorCode(value: string): value is ArtifactErrorCode {
  return (Object.values(ARTIFACT_ERROR_CODES) as readonly string[]).includes(
    value,
  );
}
