export const TRUSTED_RUNTIME_IPC_VERSION = 1 as const;

export const TRUSTED_AGENT_EXPORT_NAME = "run";

export const RuntimeErrorCode = {
  ARTIFACT_NOT_FOUND: "RUNTIME_ARTIFACT_NOT_FOUND",
  INTEGRITY_MISMATCH: "RUNTIME_INTEGRITY_MISMATCH",
  INVALID_MODULE: "INVALID_RUNTIME_MODULE",
  TIMEOUT: "RUNTIME_TIMEOUT",
  AGENT_ERROR: "AGENT_EXECUTION_ERROR",
  INVALID_OUTPUT: "INVALID_RUNTIME_OUTPUT",
  INVALID_DESCRIPTOR: "INVALID_RUNTIME_DESCRIPTOR",
  PATH_ESCAPE: "RUNTIME_PATH_ESCAPE",
} as const;

export type RuntimeErrorCode =
  (typeof RuntimeErrorCode)[keyof typeof RuntimeErrorCode];

export const CHILD_ENV_ALLOWLIST = [
  "PATH",
  "PATHEXT",
  "SYSTEMROOT",
  "SYSTEMDRIVE",
  "WINDIR",
  "COMSPEC",
  "TEMP",
  "TMP",
  "TMPDIR",
  "HOME",
  "USERPROFILE",
  "HOMEDRIVE",
  "HOMEPATH",
  "USERNAME",
  "USER",
  "LOGNAME",
  "LANG",
  "LC_ALL",
  "LC_CTYPE",
  "TZ",
  "TERM",
  "OS",
  "PROCESSOR_ARCHITECTURE",
  "NUMBER_OF_PROCESSORS",
  "LOCALAPPDATA",
  "APPDATA",
] as const;
